[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
bevy = { version = "0.6.1", default-features = false, features = ["bevy_winit", "render", "png", "hdr", "x11"] }
bevy_asset_loader = "0.9.0"
ldtk_rust = "0.5.2"
serde_json = "1.0.79"
anyhow = "1.0.56"
bevy_embedded_assets = "0.2.1"

[profile.release]
codegen-units = 1
panic = "unwind"
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3
