[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.133", features = ["derive"] }
online = { version = "3.0.1",  default-features = false, features = ["sync"] }
bevy = { version = "0.6.0", default-features = false, features = ["bevy_dynamic_plugin", "bevy_gilrs", "bevy_gltf", "bevy_winit", "render", "png", "hdr", "x11"] }
bevy_kira_audio = { version = "0.8.0", features = ["mp3", "ogg", "wav"] }
bevy_asset_loader = "0.8.0"
ldtk_rust = "0.5.2"
benimator = "1.0.0"
serde_json = "1.0.74"
anyhow = "1.0.52"

[profile.release]
codegen-units = 1
panic = "unwind"
lto = "fat"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3
