[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2018"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.130", features = ["derive"] }
online = { version = "3.0.1",  default-features = false, features = ["sync"] }
bevy = "0.5.0"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "fat"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3

