[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde_json = "1.0.82"
serde = { version = "1.0.140", features = ["derive"] }
bevy = { version = "0.8.0", default-features = false, features = ["serialize", "bevy_winit", "render", "png", "x11"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
bevy_asset_loader = "0.12.0"
bevy_kira_audio = "0.11.0"
bevy_prototype_debug_lines = { git = "https://github.com/thisjaiden/bevy_debug_lines" }
bevy_easings = "0.8.0"
bevy_embedded_assets = "0.4.0"
ldtk_rust = "0.6.0"
anyhow = "1.0.58"
tracing-subscriber = "0.3.15"
tracing-log = "0.1.3"
tracing = "0.1.36"
rand = "0.8.5"
num = "0.4.0"

[profile.release]
codegen-units = 1
panic = "unwind"
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3
strip = true
