[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
bevy = { version = "0.7.0", default-features = false, features = ["serialize", "bevy_winit", "render", "png", "hdr", "x11"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
bevy_asset_loader = "0.10.0"
ldtk_rust = { git = "https://github.com/thisjaiden/ldtk_rust.git" }
serde_json = "1.0.79"
anyhow = "1.0.56"
bevy_embedded_assets = { git = "https://github.com/vleue/bevy_embedded_assets.git" }

[profile.release]
codegen-units = 1
panic = "unwind"
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3
strip = true
