[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
online = { version = "3.0.1",  default-features = false, features = ["sync"] }
bevy = { version = "0.6.1", default-features = false, features = ["bevy_gilrs", "bevy_gltf", "bevy_winit", "render", "png", "hdr", "x11"] }
# we don't use audio... yet.
# bevy_kira_audio = { version = "0.8.0", features = ["mp3", "ogg", "wav"] }
bevy_asset_loader = "0.8.0"
ldtk_rust = "0.5.2"
benimator = "2.0.1"
serde_json = "1.0.79"
anyhow = "1.0.53"

[profile.release]
codegen-units = 1
panic = "unwind"
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3
