[package]
name = "socktile"
version = "1.0.0-closed-alpha-00"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde_json = "1.0.85"
serde = { version = "1.0.144", features = ["derive"] }
bevy = { version = "0.8.1", default-features = false, features = ["serialize", "bevy_winit", "render", "png", "x11"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
bevy_asset_loader = { version = "0.12.1", features = ["progress_tracking"] }
bevy_kira_audio = "0.12.0"
bevy_prototype_debug_lines = "0.8.1"
bevy_easings = "0.8.1"
bevy_embedded_assets = "0.4.0"
iyes_progress = "0.5.0"
ldtk_rust = "0.6.0"
anyhow = "1.0.63"
tracing-subscriber = "0.3.15"
tracing-log = "0.1.3"
tracing-wasm = "0.2.1"
tracing = "0.1.36"
rand = "0.8.5"
num = "0.4.0"
console_error_panic_hook = "0.1.7"
netty = { version = "0.1.0", path = "../netty", features = ["legacy_threaded"] }

[profile.release]
codegen-units = 1
panic = "unwind"
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = 0
opt-level = 3
strip = true
